services:
  # Nginx reverse proxy for local development
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/var/www/html/frontend:ro
    depends_on:
      - app
      - api
    restart: unless-stopped

  # Frontend development server with hot reload
  app:
    image: node:20-alpine
    ports:
      - "3000:3000"  # Direct access for development
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Anonymous volume for node_modules
    working_dir: /app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # For file watching in Docker
      - VITE_API_URL=http://localhost:8080/api  # API endpoint through nginx
    command: sh -c "npm install && npm run build && npm run dev"
    restart: unless-stopped

  # PHP-FPM API server
  api:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # Direct access for debugging
    volumes:
      - ./backend:/var/www/html/backend
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DB_HOST=mariadb
      - DB_NAME=employee_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - PHP_IDE_CONFIG=serverName=localhost  # For Xdebug
    # Simplified healthcheck for development
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 30s
    restart: unless-stopped

  # MariaDB database
  mariadb:
    image: mariadb:11.4
    ports:
      - "3306:3306"  # Direct access for database tools
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_db
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Simplified healthcheck for development
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 30s
    restart: unless-stopped

volumes:
  mariadb_data:
